# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dBetaBinomial <- function(r, n, alpha, beta, log = FALSE) {
    .Call(`_RBesT_dBetaBinomial`, r, n, alpha, beta, log)
}

.pBetaBinomial <- function(r, n, alpha, beta, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_RBesT_pBetaBinomial`, r, n, alpha, beta, lower_tail, log_p)
}

